---
spring:
  freemarker:
    template-loader-path: classpath:/templates/
  application:
    name: report-home
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.62.60.33:8913/RTI_AIRMDP
#    username: umobile
#    password: Umobile@123
    url: jdbc:mysql://10.62.49.70:8913/AIMDP
    username: msc_app
    password: msc_app@9102
    
  session:
    store-type: none
  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
    encoding: UTF-8
server:
  context-path: /report-home
  #context-path: /
  port: 9199
management:
  security:
    enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
rti:
  priv:
    exception: false
mybatis:
  mapper-locations: mapper/mysql/*.xml
  type-aliases-package: com.ai.rti.report.entity
logging:
  file: ../logs/report-svc.log 
  pattern:
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level [%C{1}:%L] - %msg%n"
  level:
    com:
      ai:
        rti:
          ic:
            tag:
              dao: debug 